apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crd.yaml
- service_account.yaml
- role.yaml
- role_binding.yaml
- operator.yaml
commonLabels:
  kustomize.component: hello-world
images:
- name: hello-world
  newName: adrian555/hello-world
  newTag: v0.0.1
- name: hello-op
  newName: adrian555/hello-op
  newTag: v0.0.1
configMapGenerator:
- name: openaihub-install-config	
  literals:	
    - DEPLOY_ENV="base"